default_language_version:
    python: python3.8
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: c8bad492e1b1d65d9126dba3fe3bd49a5a52b9d6  # v2.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: ^docs/.*$
    -   id: trailing-whitespace
        exclude: README.md
-   repo: git://github.com/PyCQA/flake8
    rev: 88caf5ac484f5c09aedc02167c59c66ff0af0068  # 3.7.7
    hooks:
    -   id: flake8
-   repo: git://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
-   repo: git://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
